shell:
    program: /bin/bash
    args:
        - -lc
        - if [[ $(/usr/bin/env tmux lsc -t main) ]]; then exec /usr/bin/env tmux new-session; else exec /usr/bin/env tmux new-session -A -s main; fi

window:
    opacity: 0.90
    decorations: none
    dimensions:
        columns: 164
        lines: 48
    padding:
        x: 0
        y: 0

mouse:
    hide_when_typing: true

font:
    normal:
        style: Regular
        #family: FuraCode Nerd Font
        #family: SauceCodePro Nerd Font
        #family: Noto Mono Nerd Font Complete
        family: UbuntuMono Nerd Font
    italic:
        style: Bold
    bold_italic:
        style: Bold Italic
    size: 12.0

visual_bell:
    animation: EaseOutExpo
    duration: 0
    color: '0xffffff'

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

cursor:
  style: Block
  unfocused_hollow: true

key_bindings:
    - { key: Return, mods: Super, action: ToggleFullscreen }
    - { key: C, mods: Super, chars: "\x00[" }
    - { key: V, mods: Super, action: Paste }
    - { key: Plus, mods: Control|Shift, action: IncreaseFontSize }
    - { key: N, mods: Super, action: SpawnNewInstance }
    - { key: A, mods: Alt, chars: "\x1ba" }
    - { key: B, mods: Alt, chars: "\x1bb" }
    - { key: C, mods: Alt, chars: "\x1bc" }
    - { key: D, mods: Alt, chars: "\x1bd" }
    - { key: E, mods: Alt, chars: "\x1be" }
    - { key: F, mods: Alt, chars: "\x1bf" }
    - { key: G, mods: Alt, chars: "\x1bg" }
    - { key: H, mods: Alt, chars: "\x1bh" }
    - { key: I, mods: Alt, chars: "\x1bi" }
    - { key: J, mods: Alt, chars: "\x1bj" }
    - { key: K, mods: Alt, chars: "\x1bk" }
    - { key: L, mods: Alt, chars: "\x1bl" }
    - { key: M, mods: Alt, chars: "\x1bm" }
    - { key: N, mods: Alt, chars: "\x1bn" }
    - { key: O, mods: Alt, chars: "\x1bo" }
    - { key: P, mods: Alt, chars: "\x1bp" }
    - { key: Q, mods: Alt, chars: "\x1bq" }
    - { key: R, mods: Alt, chars: "\x1br" }
    - { key: S, mods: Alt, chars: "\x1bs" }
    - { key: T, mods: Alt, chars: "\x1bt" }
    - { key: U, mods: Alt, chars: "\x1bu" }
    - { key: V, mods: Alt, chars: "\x1bv" }
    - { key: W, mods: Alt, chars: "\x1bw" }
    - { key: X, mods: Alt, chars: "\x1bx" }
    - { key: Y, mods: Alt, chars: "\x1by" }
    - { key: Z, mods: Alt, chars: "\x1bz" }

#
# Colors
#

# Colors (Base16 Default Dark)
colors:
  # Default colors
  primary:
    background: '0x0A0A0A'
    foreground: '0xd8d8d8'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: CellBackground
    cursor: CellForeground

  # Normal colors
  normal:
    black:   '0x181818'
    red:     '0xab4642'
    green:   '0xa1b56c'
    yellow:  '0xf7ca88'
    blue:    '0x7cafc2'
    magenta: '0xba8baf'
    cyan:    '0x86c1b9'
    white:   '0xd8d8d8'

  # Bright colors
  bright:
    black:   '0x585858'
    red:     '0xab4642'
    green:   '0xa1b56c'
    yellow:  '0xf7ca88'
    blue:    '0x7cafc2'
    magenta: '0xba8baf'
    cyan:    '0x86c1b9'
    white:   '0xf8f8f8'

## Colors (Gruvbox dark)
#colors:
#  # Default colors
#  primary:
#    # hard contrast: background = '0x1d2021'
#    background: '0x282828'
#    # soft contrast: background = '0x32302f'
#    foreground: '0xebdbb2'
#
#  # Normal colors
#  normal:
#    black:   '0x282828'
#    red:     '0xcc241d'
#    green:   '0x98971a'
#    yellow:  '0xd79921'
#    blue:    '0x458588'
#    magenta: '0xb16286'
#    cyan:    '0x689d6a'
#    white:   '0xa89984'
#
#  # Bright colors
#  bright:
#    black:   '0x928374'
#    red:     '0xfb4934'
#    green:   '0xb8bb26'
#    yellow:  '0xfabd2f'
#    blue:    '0x83a598'
#    magenta: '0xd3869b'
#    cyan:    '0x8ec07c'
#    white:   '0xebdbb2'
