# Send ESC (\x1b) before characters when alt is pressed.
alt_send_esc: true

shell:
    program: /bin/bash
    args:
        - -lc
        - if [[ $(/usr/bin/tmux lsc -t main) ]]; then exec /usr/bin/tmux new-session; else exec /usr/bin/tmux new-session -A -s main; fi

window:
    opacity: 0.90
    decorations: none
    dimensions:
        columns: 164
        lines: 48
    padding:
        x: 0
        y: 0

mouse:
    hide_when_typing: true

font:
    normal:
        style: Regular
        #family: FuraCode Nerd Font
        #family: SauceCodePro Nerd Font
        #family: Noto Mono Nerd Font Complete
        family: UbuntuMono Nerd Font
    italic:
        style: Bold
        family: Ubuntu Mono
    bold_italic:
        style: Bold Italic
        family: Ubuntu Mono
    size: 12.0

visual_bell:
    animation: EaseOutExpo
    duration: 0
    color: '0xffffff'

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

cursor:
  style: Block
  unfocused_hollow: true

key_bindings:
    - { key: Return, mods: Super, action: ToggleFullscreen }
    - { key: C, mods: Super, chars: "\x00[" }
    - { key: V, mods: Super, action: Paste }
    - { key: Plus, mods: Control|Shift, action: IncreaseFontSize }

#
# Colors
#

# Colors (Base16 Default Dark)
colors:
  # Default colors
  primary:
    background: '0x0A0A0A'
    foreground: '0xd8d8d8'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: CellBackground
    cursor: CellForeground

  # Normal colors
  normal:
    black:   '0x181818'
    red:     '0xab4642'
    green:   '0xa1b56c'
    yellow:  '0xf7ca88'
    blue:    '0x7cafc2'
    magenta: '0xba8baf'
    cyan:    '0x86c1b9'
    white:   '0xd8d8d8'

  # Bright colors
  bright:
    black:   '0x585858'
    red:     '0xab4642'
    green:   '0xa1b56c'
    yellow:  '0xf7ca88'
    blue:    '0x7cafc2'
    magenta: '0xba8baf'
    cyan:    '0x86c1b9'
    white:   '0xf8f8f8'

## Colors (Gruvbox dark)
#colors:
#  # Default colors
#  primary:
#    # hard contrast: background = '0x1d2021'
#    background: '0x282828'
#    # soft contrast: background = '0x32302f'
#    foreground: '0xebdbb2'
#
#  # Normal colors
#  normal:
#    black:   '0x282828'
#    red:     '0xcc241d'
#    green:   '0x98971a'
#    yellow:  '0xd79921'
#    blue:    '0x458588'
#    magenta: '0xb16286'
#    cyan:    '0x689d6a'
#    white:   '0xa89984'
#
#  # Bright colors
#  bright:
#    black:   '0x928374'
#    red:     '0xfb4934'
#    green:   '0xb8bb26'
#    yellow:  '0xfabd2f'
#    blue:    '0x83a598'
#    magenta: '0xd3869b'
#    cyan:    '0x8ec07c'
#    white:   '0xebdbb2'
