# Send ESC (\x1b) before characters when alt is pressed.
alt_send_esc: true

font:
    normal:
        family: SauceCodePro Nerd Font Mono
    size: 12.0

visual_bell:
    animation: EaseOutExpo
    duration: 0
    color: '0xffffff'

background_opacity: 0.9

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: false

cursor:
  # Cursor style
  #
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

#
# Colors
#

# Colors (Base16 Default Dark)
colors:
  # Default colors
  primary:
    background: '0x181818'
    foreground: '0xd8d8d8'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xd8d8d8'
    cursor: '0xd8d8d8'

  # Normal colors
  normal:
    black:   '0x181818'
    red:     '0xab4642'
    green:   '0xa1b56c'
    yellow:  '0xf7ca88'
    blue:    '0x7cafc2'
    magenta: '0xba8baf'
    cyan:    '0x86c1b9'
    white:   '0xd8d8d8'

  # Bright colors
  bright:
    black:   '0x585858'
    red:     '0xab4642'
    green:   '0xa1b56c'
    yellow:  '0xf7ca88'
    blue:    '0x7cafc2'
    magenta: '0xba8baf'
    cyan:    '0x86c1b9'
    white:   '0xf8f8f8'

## Colors (Gruvbox dark)
#colors:
#  # Default colors
#  primary:
#    # hard contrast: background = '0x1d2021'
#    background: '0x282828'
#    # soft contrast: background = '0x32302f'
#    foreground: '0xebdbb2'
#
#  # Normal colors
#  normal:
#    black:   '0x282828'
#    red:     '0xcc241d'
#    green:   '0x98971a'
#    yellow:  '0xd79921'
#    blue:    '0x458588'
#    magenta: '0xb16286'
#    cyan:    '0x689d6a'
#    white:   '0xa89984'
#
#  # Bright colors
#  bright:
#    black:   '0x928374'
#    red:     '0xfb4934'
#    green:   '0xb8bb26'
#    yellow:  '0xfabd2f'
#    blue:    '0x83a598'
#    magenta: '0xd3869b'
#    cyan:    '0x8ec07c'
#    white:   '0xebdbb2'
