# According to:
# http://superuser.com/questions/789448/choosing-between-bashrc-profile-bash-profile-etc
#
#   * ~/.bash_profile should be super-simple and just load .profile and
#     .bashrc (in that order)

source $HOME/.profile
source $HOME/.bashrc

if [ -f "$HOME/.cargo/env" ]; then
    source "$HOME/.cargo/env"
fi
