# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

export GITAWAREPROMPT="$HOME/.bash/git-aware-prompt"
source $GITAWAREPROMPT/main.sh

# set a fancy prompt (non-color, unless we know we "want" color)
color_prompt="\[$bldgrn\]\u@\h\[$txtrst\]:\[$bldblu\]\w\[$txtrst\] \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]\$ "
case "$TERM" in
xterm-color|xterm-256color)
    export PS1="$color_prompt"
    ;;
xterm)
    export PS1="$color_prompt"
    ;;
screen)
    export PS1="$color_prompt"
    ;;
*)
    PS1='\T \u@\h:\w\$ '
    ;;
esac

# Comment in the above and uncomment this below for a color prompt
#PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

#if [ -f ~/.bash_aliases ]; then
#    . ~/.bash_aliases
#fi

# enable color support of ls and also add handy aliases
#if [ "$TERM" != "dumb" ]; then
    #eval "`dircolors -b`"
    #alias ls='ls --color=always'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'
#fi

# some more ls aliases
if [ $(uname) = "Darwin" ] ; then
   alias ls='ls -G'
else
   alias ls='ls --color'
fi
alias ll='ls -l'
alias llh='ll -h'
#alias la='ls -A'
#alias l='ls -CF'

alias screen="screen -T xterm-color"

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# Take in all the custom completions too.
if [ -f ~/Dropbox/Documents/LinuxEnvironment/bash_completion ]; then
    for F in "$(ls ~/Dropbox/Documents/LinuxEnvironment/bash_completion/*.bash)"; do
        if [ -f "$F" ]; then
            . "$F"
        fi
    done
fi

export EDITOR=vim
export PATH=$PATH:~/bin:~/scripts:/usr/local/bin:/usr/local/sbin

alias grepsource="find . -name *.[ch] | xargs grep -n "

alias sync_betascore="rsync -avz --exclude-from=/Users/heewa/src/betascout/config/rsync_excludes "

#alias fin="if [ \$? = 0 ]; then ssh heewa@heewa-dev1 -t \"DISPLAY=:0.0 /usr/bin/notify-send 'Done' '$USER@$HOSTNAME' -i face-smile -t 1000000\"; true; else ssh heewa@heewa-dev1 -t \"DISPLAY=:0.0 /usr/bin/notify-send --urgency=critical 'Done FAILED' '$USER@$HOSTNAME' -i face-angry -t 1000000\"; false; fi"
#alias done="if [ \$? = 0 ]; then echo true; else echo false; fi"

# On mac, there are files in /etc/paths.d/ that contain more paths. Add them manually for screen's benefit.
if [[ $IN_SCREEN && $(uname) == 'Darwin' ]]; then
    export PATH=$PATH:$(cat /etc/paths.d/* | tr \\n : | sed 's/:\s*$//')
fi


#####
##### Git
#####
alias gitfiles="git status -s | grep '^ M ' | sed -e 's:^...::'"


# Colorize the Terminal for Mac
export CLICOLOR=1;


PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

##
# Android SDK Development
##
export PATH=$PATH:~/src/android/sdk/tools
export PATH=$PATH:~/src/android/sdk/platform-tools
export ANDROID_HOME=$PATH:~/src/android/sdk

