#!/bin/bash

echo 'notmuch: processing new mail'
/usr/bin/notmuch new

echo "$(/usr/bin/notmuch count tag:tofilter) new mail to filter"

/usr/bin/notmuch tag +unsubscribe -inbox from:heewa.b@gmail.com and 'body:"This message was automatically generated by Gmail."'
/usr/bin/notmuch tag +git 'from:notifications@github.com or from:gitlab-issues@'

#
# Add/Remove gmail-label tags from mail not/in label folders
#

/usr/bin/notmuch tag +tax folder:heewab/Reference/Tax
/usr/bin/notmuch tag -tax tag:tax not folder:heewab/Reference/Tax

/usr/bin/notmuch tag +doc folder:heewab/Reference/Documents
/usr/bin/notmuch tag -doc tag:doc not folder:heewab/Reference/Documents

/usr/bin/notmuch tag +employ folder:heewab/Reference/Employment
/usr/bin/notmuch tag -employ tag:employ not folder:heewab/Reference/Employment

/usr/bin/notmuch tag +health folder:heewab/Reference/Health
/usr/bin/notmuch tag -health tag:health not folder:heewab/Reference/Health

/usr/bin/notmuch tag +job folder:heewab/Reference/JobSearch
/usr/bin/notmuch tag -job tag:job not folder:heewab/Reference/JobSearch

/usr/bin/notmuch tag +receipt folder:heewab/Reference/Receipts
/usr/bin/notmuch tag -receipt tag:receipt not folder:heewab/Reference/Receipts

/usr/bin/notmuch tag +ref folder:heewab/Reference/Reference
/usr/bin/notmuch tag -ref tag:ref not folder:heewab/Reference/Reference

/usr/bin/notmuch tag +record :heewab/Reference/Records
/usr/bin/notmuch tag -record tag:record not :heewab/Reference/Records

# Untag emails that need to be filtered
/usr/bin/notmuch tag -tofilter tag:tofilter

echo 'Finished tagging mail'
