#!/bin/bash

/usr/bin/notmuch new

/usr/bin/notmuch count tag:tofilter and tag:unread

/usr/bin/notmuch tag +unsubscribe -inbox tag:tofilter and from:heewa.b@gmail.com and 'body:"This message was automatically generated by Gmail."'
/usr/bin/notmuch tag +git 'tag:tofilter and (from:notifications@github.com or from:gitlab-issues@)'

/usr/bin/notmuch tag -tofilter tag:tofilter
