#!/bin/bash

/usr/bin/notmuch new

/usr/bin/notmuch count tag:tofilter

/usr/bin/notmuch tag +unsubscribe -inbox from:heewa.b@gmail.com and 'body:"This message was automatically generated by Gmail."'
/usr/bin/notmuch tag +git 'from:notifications@github.com or from:gitlab-issues@'

/usr/bin/notmuch tag +tax folder:heewab/Reference/Tax
/usr/bin/notmuch tag +doc folder:heewab/Reference/Documents
/usr/bin/notmuch tag +employ folder:heewab/Reference/Employment
/usr/bin/notmuch tag +health folder:heewab/Reference/Health
/usr/bin/notmuch tag +job folder:heewab/Reference/JobSearch
/usr/bin/notmuch tag +receipt folder:heewab/Reference/Receipts
/usr/bin/notmuch tag +ref folder:heewab/Reference/Reference
/usr/bin/notmuch tag +record :heewab/Reference/Records

/usr/bin/notmuch tag -tofilter tag:tofilter
